API_Stripe/API_Stripe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('payment.urls', namespace='payment')),
]

API_Stripe/payment/urls.py
from django.urls import path, include
from . import views 


app_name = 'payment'
urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/signup/', views.SignUpView.as_view(), name='signup'),
    path('currency/', views.currency, name='currency'),
    path('catalog/', views.catalog, name='catalog'),
    path('item/<int:item_id>', views.get_item, name='item_detail'),
    path('cart/delete', views.delete_order, name='delete'),
    path('cart/', views.cart, name='cart'),
    path('buy/', views.buy_item, name='buy'),
    path('success/', views.success, name='success'),
    path('cancel/', views.cancel, name='cancel'),
    path("accounts/", include("django.contrib.auth.urls"))
]

API_Stripe/payment/models.py
from decimal import Decimal
from django.db import models
from django.core.validators import MinValueValidator
from django.contrib.auth.models import User


class Item(models.Model):  
    CURRENCIES = {
        'rub': 'руб',
        'usd': 'USD'
    }
         
    name = models.CharField(max_length=255, verbose_name='Название')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    price = models.DecimalField(
        max_digits=10, 
        decimal_places=2, 
        validators=[MinValueValidator(Decimal('0.50'))], 
        verbose_name='Стоимость'
        )
    currency = models.CharField(
        max_length=3, 
        choices=CURRENCIES, 
        default='rub', 
        verbose_name='Валюта', 
        )
    
    def __str__(self) -> str:
        return self.name
    
    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['name']
        indexes = [models.Index(fields=['name'])]
        
    
    
class Discount(models.Model):
    DURATION = {
        'frv': 'forever',
        'once': 'once',
        'rpt': 'repeating'
    }
    
    name = models.CharField(max_length=100, unique=True, verbose_name='Название купона')
    duration = models.CharField(max_length=4, choices=DURATION, default='once', verbose_name='Продолжительность')
    discount = models.DecimalField(
        default=0.01,
        max_digits=4, 
        decimal_places=2, 
        validators=[MinValueValidator(Decimal('0.01'))], 
        verbose_name='Скидка в %'
    )

    def __str__(self) -> str:
        return f'Купон {self.name} на {self.discount}%, продолжительностю {self.DURATION[self.duration]}'
    
    class Meta:
        verbose_name = 'Скидка'
        verbose_name_plural = 'Скидки'
    

class Tax(models.Model):
    name = models.CharField(max_length=100, default='НДС', verbose_name='Название налога')
    inclusive = models.BooleanField(
        default=False, 
        verbose_name='Инклюзивная ставка', 
        help_text='Указывает, является ли ставка налога инклюзивной или эксклюзивной')
    country = models.CharField(
        max_length=2, 
        default='RU', 
        blank=True, 
        null=True, 
        verbose_name='Код страны', 
        help_text='(ISO 3166-1 alpha-2)')
    tax = models.DecimalField(
        default=0.01,
        max_digits=4,
        decimal_places=2,
        validators=[MinValueValidator(Decimal('0.01'))],
        verbose_name='Налог в %'
    )
    
    
    def __str__(self) -> str:
        return f'{self.name} - {self.tax}%'
    
    class Meta:
        verbose_name = 'Налог'
        verbose_name_plural = 'Налоги'
    
        
class Order(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Покупатель')
    discount = models.ForeignKey(
        Discount,
        blank=True,
        null=True,
        on_delete=models.SET_NULL, 
        related_name='order_disc', 
        verbose_name='Скидка'
    )
    tax = models.ForeignKey(
        Tax,
        blank=True,
        null=True,
        on_delete=models.SET_NULL, 
        related_name='order_tax',
        verbose_name='Налог'
    )
    total = models.DecimalField(
        default = 0.50,
        max_digits=10, 
        decimal_places=2,
        validators=[MinValueValidator(Decimal('0.50'))], 
        verbose_name='Итоговая сумма'
        )
    order_currency = models.CharField(
        max_length=3, 
        choices=Item.CURRENCIES, 
        default='rub',
        verbose_name='Валюта корзины',
        )
    
    def __str__(self) -> str:
        return f'Корзина пользователя {self.user}'
    
    class Meta:
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзины'
        

class OrderItems(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='item', verbose_name='Корзина')
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='order', verbose_name='Товар')
    quantity = models.IntegerField(default=1, verbose_name='Количество')
    
    def __str__(self) -> str:
        return f'{self.order} c товаром {self.item} в количестве {self.quantity} шт.'
    
    class Meta:
        unique_together = ('order', 'item')
        verbose_name = 'Товар корзины'
        verbose_name_plural = 'Товары корзины'
        

API_Stripe/payment/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=200)
    password1 = forms.CharField(max_length=50, widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50, widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

API_Stripe/payment/views.py
from django.http import JsonResponse, Http404, HttpResponseBadRequest
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
import stripe

from .models import Item, Order, Discount, OrderItems, Tax
from .forms import SignUpForm

from API_Stripe.settings import STRIPE_PUBLISHABLE_KEY as publish_key,\
    STRIPE_SECRET_KEY as secret_key, STRIPE_VERSION as version


stripe.api_key = secret_key
stripe.api_version = version


def has_or_create_coupon(discount: Discount) -> stripe._coupon.Coupon | None:
    """Проверка существования купона в Stripe, если не найден - создается"""
    if discount:
        for coupon in stripe.Coupon.list()['data']:
            if discount.name == coupon['id']:
                break
        else:
            coupon = stripe.Coupon.create(
                duration=discount.duration,
                id=discount.name,
                percent_off=discount.discount,
            )
        return coupon
    return
            
def has_or_create_tax(tax_rate: Tax) -> stripe._tax_rate.TaxRate | None:
    """Проверка существования налога в Stripe, если не найден - создается"""
    if tax_rate:
        for tax in stripe.TaxRate.list()['data']:
            if tax_rate.name == tax['display_name']:
                break
        else:
            tax = stripe.TaxRate.create(
                display_name=tax_rate.name,
                percentage=tax_rate.tax,
                inclusive=tax_rate.inclusive,
                country=tax_rate.country,
            )
        return tax
    return

# def create_session(line_items: list[dict], 
#                    order: Order, 
#                    discount: stripe._coupon.Coupon
#                    ) -> stripe.checkout._session.Session:
#     """Создание платежной сессии"""
#     user_name = order.user

#     if discount:
#         discounts = [{'coupon': discount.id}]
#     else:
#         discounts = []
#     checkout_session = stripe.checkout.Session.create(
#             payment_method_types=['card'], 
#             line_items=line_items,
#             metadata={
#                 'product_id': order.id
#             },
#             mode='payment',
#             discounts=discounts,
#             success_url=f'http://127.0.0.1:8000/success/{user_name}', 
#             cancel_url='http://127.0.0.1:8000/cancel/'
#         )
#     return checkout_session

def create_payment_intent(order: Order,
                          discount: stripe._coupon.Coupon,
                          tax_rate: stripe._tax_rate.TaxRate,
                          ) -> stripe.PaymentIntent:
    """Создание Payment Intent"""
    
    payment_intent_args = {
        'amount': int(order.total * 100),
        'currency': order.order_currency,
        'metadata': {
            'order_id': order.id  # Сохраняем идентификатор заказа в метаданных
        }
    }

    # Если указана ставка налога, добавляем её в метаданные
    if tax_rate:
        payment_intent_args['metadata']['tax_rates'] = tax_rate.id

    # Если есть скидка, добавляем её в метаданные
    if discount:
        payment_intent_args['metadata']['discount_coupon'] = discount.id

    try:
        payment_intent = stripe.PaymentIntent.create(**payment_intent_args)
    except:
        return HttpResponseBadRequest('<h1>При создании Payment Intent были переданы некорректные данные</h1>')
    return payment_intent

def index(request):
    if request.user.is_authenticated:
            return redirect(to='/currency/')
    return render(request, 'payment/index.html')

class SignUpView(generic.CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy('payment:login')
    template_name = 'registration/signup.html'
    
    def dispatch(self, request, *args, **kwargs):
        # перенаправит на домашнюю страницу, если пользователь попытается получить доступ к странице регистрации после авторизации
        if request.user.is_authenticated:
            return redirect(to='/currency/')

        return super(SignUpView, self).dispatch(request, *args, **kwargs)


def currency(request):
    """Вывод каталога товаров из БД"""
    if request.method == 'POST':
        currency = request.POST.get('currency')
        order = Order.objects.get(user=request.user)
        if order.item.all() and order.order_currency != currency:
            return HttpResponseBadRequest('<h1>В вашей корзине есть товары другой валюты, пожалуйста выберите валюту корзины</h1>')
        order.order_currency = currency
        order.save()
        return redirect('payment:catalog')
    else:
        if request.user.is_authenticated:
            Order.objects.get_or_create(user=request.user)
        return render(request, 'payment/catalog.html', {'currencies': Item.CURRENCIES})


def catalog(request):
    items = Item.objects.all()
    order = Order.objects.get(user=request.user)
    return render(request, 'payment/catalog.html', 
                  {'items': items, 'user': order.user, 'currency': order.order_currency})


def get_item(request, item_id: int):
    """Вывод информации о выбранном товаре и добавление его в корзину"""
    if request.method == 'POST':
        try:
            quantity = int(request.POST.get('quantity')) # получаем кол-во товаров для добавления в корзину
        except ValueError:
            quantity = 1
        if quantity <= 0:
            return HttpResponseBadRequest('Значение должно быть больше 0')
        
        item = Item.objects.get(pk=item_id)
        order = Order.objects.get(user=request.user)
            
        # если товар имеет другую валюту - не попадает в корзину
        if item.currency != order.order_currency: 
            return render(request,
                            'payment/status.html',
                            {'response': 
                                    'Валюта товара не совпадает с валютой товаров в корзине'})
        
        order_item, created = OrderItems.objects.get_or_create(order=order, item=item)
        if not created: # если товар есть в корзине добавляем указанное количество 
            order_item.quantity += quantity
        else: # иначе создаем новый товар с указанным количеством
            order_item.quantity = quantity
        order_item.save()
        return render(request, 'payment/status.html', {'response': 'Товар добавлен в корзину'})
    
    # Вывод информации о товаре
    else: 
        try:
            item = Item.objects.get(pk=item_id)
        except Item.DoesNotExist:
            raise Http404(f'Товара с id={item_id} не существует')
        return render(request, 'payment/item.html', {'item': item}) 


def buy_item(request):
    """Отправка запроса Stripe Payment Intent на получение client_secret и его передача на фронтенд"""
    # """Отправка запроса Stripe Session на получение session_id и его передача на фронтенд"""
    order = Order.objects.get(user=request.user)
    
    discount_model = order.discount
    tax_rate_model = order.tax
    # items = order.item.all()
    
    # Проверка на существование купона и налога в Stripe
    tax_rate = has_or_create_tax(tax_rate_model)
    discount = has_or_create_coupon(discount_model)

    payment_intent = create_payment_intent(order, discount, tax_rate)
    return JsonResponse({'client_secret': payment_intent['client_secret']})
    # line_items = []
    
    # Создаем список товаров для передачи Stripe
    # for item in items:
    #     quantity = item.quantity
    #     item = Item.objects.get(pk=item.item_id)
    #     line_items.append({'price_data': {'currency': item.currency,
    #                                 'product_data': {
    #                                     'name': item.name, 
    #                                     'description': item.description or None
    #                                 }, 
    #                                 'unit_amount': int(item.price * 100)}, # Сумма в копейках
    #                        'tax_rates': [tax_rate.id], 'quantity': quantity})

    # checkout_session = create_session(line_items, order, discount)
    
    # return JsonResponse({'id': checkout_session.id})

def success(request):
    """Ответ при успешной оплате и очищение корзины"""
    order = Order.objects.get(user=request.user)
    order.total = 0
    order.save()
    OrderItems.objects.filter(order=order).delete()
    return render(request, 'payment/status.html', {'response': 'Оплата произошла успешно'})

def cancel(request):
    """Ответ при неудачной оплате"""
    return render(request, 'payment/status.html', {'response': 'Оплата была отменена'})

def cart(request):
    """Корзина пользователя"""
    order = Order.objects.get(user=request.user)
    user_items = [(Item.objects.get(pk=order_item.item_id), order_item.quantity) \
        for order_item in order.item.all()]
    amount = 0
    
    # Проверка на существование купона и налога в Stripe
    tax_rate = has_or_create_tax(order.tax)
    discount = has_or_create_coupon(order.discount)
    
    # Если в корзине есть товары подсчитываем сумму с учетом скидки и налога
    if user_items:

        for item, quantity in user_items:
            amount += item.price * quantity
        
        if discount:
            discount_total = round(amount * order.discount.discount / 100, 2)
        else:
            discount_total = 0
            
        total = amount - discount_total 
        
        if tax_rate:
            tax = round(total * order.tax.tax / 100, 2)
        else:
            tax = 0
            
        total += tax
        
        order.total = total
        order.save()
        
        return render(request, 'payment/cart.html', {
            'user_cart': order, 
            'user_items': user_items, 
            'amount': amount, 
            'total': total,
            'tax': tax,
            'discount': discount_total,
            'publish_key': publish_key
        })
    else:
        return render(request, 'payment/status.html', {'response': 'Корзина пустая'})
    

API_Stripe/payment/templates/payment/cart.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <title> Корзина </title>
    <script src="https://js.stripe.com/v3/"></script>
    <link type="text/css" href="{% static 'payment/css/styles.css' %}" rel="stylesheet" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
    <h1>{{ user_cart }}</h1>
    <ul>
        {% for item in user_items %}
        <li>
            <a href="http://127.0.0.1:8000/item/{{ item.id }}">
                {{ item.0 }}
            </a>
            <span>, Цена: {{ item.0.price }} {{ item.0.currency }}, Количество: {{ item.1 }}</span>
        </li>
        <br>
        {% endfor %}
    </ul>
    <p>Всего: {{ amount }} {{ user_cart.order_currency }}</p>
    <p>Скидка: {{ discount }} {{ user_cart.order_currency }}</p>
    <p>Налог: {{ tax }} {{ user_cart.order_currency }}</p>
    <p>Итого: {{ total }} {{ user_cart.order_currency }}</p>
    <br>
    <!-- <button type="button" id="checkout-button">Buy</button> -->
    <form id="payment-form">
        <div id="card-element"></div>
        <br>
        <button id="checkout-button">Оплатить</button>
        <div id="card-errors" role="alert"></div>
    </form>
    {% csrf_token %}
    <!--Передача Stripe платежных данных карты при нажатии на кнопку "Оплатить"-->
    <script type="text/javascript">
        const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;

        // Передача объекту Stripe публичного ключа
        var stripe = Stripe("{{ publish_key }}");
        var elements = stripe.elements();

        // Создание элемента карты
        var cardElement = elements.create('card');
        cardElement.mount('#card-element');

        // Обработка ошибок ввода
        cardElement.on('change', function (event) {
            var errorElement = document.getElementById('card-errors');
            if (event.error) {
                errorElement.textContent = event.error.message;
            } else {
                errorElement.textContent = '';
            }
        });

        var checkoutButton = document.getElementById("checkout-button");
        checkoutButton.addEventListener("click", function (event) {
            event.preventDefault(); // Предотвращаем стандартное поведение кнопки
            // отправляем на бэкэнд запрос на получение client_secret
            fetch("{% url 'payment:buy' %}", {
                method: "POST",
                headers: {
                    'X-CSRFToken': csrftoken
                }
            })
                .then(function (response) {
                    return response.json();
                })
                // Обработка Payment Intent
                .then(function (data) {
                    // Используем client_secret для подтверждения платежа
                    return stripe.confirmCardPayment(data.client_secret, {
                        payment_method: {
                            card: cardElement,
                        }
                    });
                })
                // Редирект на Stripe session форму
                // .then(function (session) {
                //     return stripe.redirectToCheckout({ sessionId: session.id }); 
                // })
                .then(function (result) {
                    // Обработка результата платежа
                    if (result.error) {
                        // Показать ошибку, если платеж не прошел
                        alert(result.error.message);
                    } else {
                        // Если платеж успешен происходит очистка корзины и перенаправление пользователя
                        if (result.paymentIntent.status === 'succeeded') {
                            window.location.href = "http://{{ request.get_host }}{% url 'payment:success' %}";
                        }
                    }
                })
                .catch(function (error) {
                    console.error("Ошибка при обработке платежа:", error);
                });
        });
    </script>
    <br>
    {% include 'payment/return.html' %}
    <br>
    <form action="{% url 'payment:delete' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Очистить корзину">
    </form>
</body>

</html>

API_Stripe/payment/templates/payment/catalog.html
<!DOCTYPE html>
<html>
<head>
    <title>Магазин</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    {% if items %}
    <h1>Каталог товаров {{ currency }}</h1>
    <ul>
        {% for item in items %}
        {% if item.currency == currency %}
        <li>
            <a href="{% url 'payment:item_detail' item.id %}">
                {{ item.name }}
            </a>
            <span> - Цена: {{ item.price }} {{ item.currency }}</span>
        </li>
        <br>
        {% endif %}
        {% endfor %}
    </ul>
    <form action="{% url 'payment:cart' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Корзина товаров">
    </form>
    <form action="{% url 'payment:currency' %}" method="get">
        <input type="submit" value="Выбрать другую валюту корзины">
    </form>
    <form action="{% url 'payment:logout' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Выйти из аккаунта">
    </form>
    {% else %}
    <form method="post">
        {% csrf_token %}
        <label for="currency">Выбери валюту платежей:</label>
        <select id="currency" name="currency">
            {% for code, currency in currencies.items %}
            <option value="{{ code }}">{{ currency }}</option>
            {% endfor %}
        <input type='submit' value='Перейти в каталог'>
    </form>
    {% endif %}
</body>
</html>

API_Stripe/payment/templates/payment/index.html
<!DOCTYPE html>
<html>

<head>
    <title>Авторизация</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
    <h2>Вход в каталог</h2>
    <form action="{% url 'payment:login' %}">
        <input type="submit" value="Войти в аккаунт">
    </form>
    <form action="{% url 'payment:signup' %}">
        <input type="submit" value="Зарегистрироваться">
    </form>
</body>

API_Stripe/payment/templates/payment/item.html
<!DOCTYPE html>
<html>

<head>
    <title>{{ item.name }}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
    <section>
        <form method="post">
            {% csrf_token %}
            <h1>{{ item.name }}</h1>
            <p>Цена: {{ item.price }} {{ item.currency }}</p>
            <p>Описание: {{ item.description }}</p>

            <label for="positive-number">Количество:</label>
            <input type="number" id="positive-number" name="quantity" min="1">
            <br>
            <br>

            <button type="submit" name="item" value="{{ item.id }}">Добавить в корзину</button>
        </form>
        <br>
        {% include 'payment/return.html' %}
    </section>
</body>
</html>

API_Stripe/payment/templates/payment/return.html
<form action="{% url 'payment:catalog' %}">
    <input type="submit" value="Вернуться в каталог товаров">
</form>

API_Stripe/payment/templates/payment/status.html
<!DOCTYPE html>
<html>

<head>
    <title>Статус оплаты</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
    <h2>
        {{response}}
    </h2>
    {% include 'payment/return.html' %}
</body>
</html>